# 1 Instant Loans

In [84]:
!pip install bs4

Requirement already satisfied: bs4 in /usr/local/lib/python3.6/dist-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.6/dist-packages (from bs4) (4.6.3)

In [0]:
# import packages
import bs4 as bs
import urllib.request
import pandas as pd

source = urllib.request.urlopen('https://www.bankbazaar.com/personal-loan/instant-loans.html').read()

In [0]:
soup = bs.BeautifulSoup(source,'lxml')

In [0]:
table = soup.find('table', attrs={'class':'table table-bordered'})
res = []
table_rows = table.find_all('tr')
for tr in table_rows:
  td = tr.find_all('td')
  row = [tr.text.strip() for tr in td if tr.text.strip()]
  if row:
    res.append(row)
df = pd.DataFrame(res, columns=res[0])

df.drop(df.head(1).index, inplace=True)

In [98]:
df

              Apps  ...                                      Interest Rate
1         PaySense  ...                                    18% to 36% p.a.
2        Rupeelend  ...                                    30% for 30 days
3            CASHe  ...  1.75% onwards for 15-day loan\n3.25% onwards f...
4       Money View  ...                                    1.33% - 2% p.m.
5            Credy  ...                                     1% - 1.5% p.m.
6      EarlySalary  ...                                          2.5% p.m.
7          LazyPay  ...                                     15% - 32% p.a.
8          mPokket  ...                            Based on lender’s terms
9   MoneyinMinutes  ...                                0.1% - 0.7% per day
10     QuickCredit  ...                                         1% per day
11      FlexSalary  ...                                 Up to 3% per month

[11 rows x 3 columns]

# 2.Gold Loans

In [0]:
source = urllib.request.urlopen('https://www.paisabazaar.com/gold-loan/interest-rates/').read()
soup = bs.BeautifulSoup(source,'lxml')

In [0]:
table = soup.find('table', attrs={'width':'98%'})
res = []
table_rows = table.find_all('tr')
for tr in table_rows:
  td = tr.find_all('td')
  row = [tr.text.strip() for tr in td if tr.text.strip()]
  if row:
    res.append(row)
df = pd.DataFrame(res, columns=res[0])

df.drop(df.head(1).index, inplace=True)

In [103]:
df

     Gold Loan Provider    Interest Rate                  Processing fee
1        HDFC Gold Loan     10.50% – 15%    0.50% -2% of the loan amount
2   Axis Bank Gold Loan  14.75% – 17.25%           1% of the loan amount
3    YES Bank Gold Loan   10.50% onwards   0.50% – 2% of the loan amount
4  Manappuram Gold Loan        Up to 29%  Varies on a case by case basis
5     Muthoot Gold Loan      12% onwards  0.25% to 1% of the loan amount
6         SBI Gold Loan   11.05% onwards         0.5% of the loan amount
7  ICICI Bank Gold Loan   10.50% onwards           1% of the loan amount

# 3. LAP

In [0]:
source = urllib.request.urlopen('https://www.paisabazaar.com/loan-against-property/interest-rates/').read()
soup = bs.BeautifulSoup(source,'lxml')

In [107]:
table = soup.find_all('table')
table[1]

<table><tbody><tr><td><strong>Loan Against Property Provider</strong></td><td><strong>Loan Against Property Interest rate</strong></td><td><strong>Processing Fee</strong></td></tr><tr><td><strong><a href="https://www.paisabazaar.com/citibank/loan-against-property/">CitiBank</a></strong></td><td>8.80% onwards</td><td> Upto 0.5 % of the loan amount +GST</td></tr><tr><td><strong><a href="https://www.paisabazaar.com/syndicate-bank/loan-against-property/">Syndicate Bank</a></strong></td><td>11.50% onwards</td><td> 0.5 % of the loan amount – Minimum ₹ 500/-+GST</td></tr><tr><td><strong><a href="https://www.paisabazaar.com/hdfc-bank/loan-against-property/">HDFC Ltd.</a></strong></td><td>9.50% onwards</td><td>Up to 1.50% of loan amount or Rs. 4,500, whichever is higher</td></tr><tr><td><strong><a href="https://www.paisabazaar.com/sbi-bank/loan-against-property/">State Bank of India</a></strong></td><td>9.60% onwards</td><td>1% of loan amount (Max. of Rs. 50,000)</td></tr><tr><td><strong><a href="https://www.paisabazaar.com/kotak-mahindra-bank/loan-against-property/">Kotak Mahindra Bank</a></strong></td><td>9.60% onwards</td><td>Up to 3% of loan amount</td></tr><tr><td><strong><a href="https://www.paisabazaar.com/icici-bank/loan-against-property/">ICICI Bank</a></strong></td><td>9.80% onwards</td><td>1% of loan amount</td></tr><tr><td><strong><a href="https://www.paisabazaar.com/idbi-bank/loan-against-property/">IDBI Bank</a></strong></td><td>10.10% onwards</td><td>Up to 0.50% of loan amount</td></tr><tr><td><a href="https://www.paisabazaar.com/bajaj-finserv/loan-against-property/"><strong>Bajaj Finserv</strong></a></td><td>10.10% onwards</td><td>Up to 1.5% of loan amount</td></tr><tr><td><strong><a href="https://www.paisabazaar.com/pnb-housing/loan-against-property/">PNB Housing Finance Ltd.</a></strong></td><td>10.25% onwards</td><td>Up to 2% of loan amount</td></tr><tr><td><strong><a href="https://www.paisabazaar.com/tata-capital/loan-against-property/">Tata Capital</a></strong></td><td>10.50% onwards</td><td>Up to 2% of loan amount</td></tr><tr><td><strong><a href="https://www.paisabazaar.com/lic-housing-finance/loan-against-property/">LIC Housing Finance Ltd.</a></strong></td><td>11.30% onwards</td><td>1% of loan amount</td></tr><tr><td><strong><a href="https://www.paisabazaar.com/axis-bank/loan-against-property/">Axis Bank</a></strong></td><td>11.35% onwards</td><td>Rs. 10,000 or 1% of loan amount, whichever is high</td></tr></tbody></table>

In [0]:
table = soup.find_all('table')
table = table[1]
res = []
table_rows = table.find_all('tr')
for tr in table_rows:
  td = tr.find_all('td')
  row = [tr.text.strip() for tr in td if tr.text.strip()]
  if row:
    res.append(row)
df = pd.DataFrame(res, columns=res[0])

df.drop(df.head(1).index, inplace=True)

In [110]:
df

   Loan Against Property Provider  ...                                     Processing Fee
1                        CitiBank  ...                 Upto 0.5 % of the loan amount +GST
2                  Syndicate Bank  ...     0.5 % of the loan amount – Minimum ₹ 500/-+GST
3                       HDFC Ltd.  ...  Up to 1.50% of loan amount or Rs. 4,500, which...
4             State Bank of India  ...             1% of loan amount (Max. of Rs. 50,000)
5             Kotak Mahindra Bank  ...                            Up to 3% of loan amount
6                      ICICI Bank  ...                                  1% of loan amount
7                       IDBI Bank  ...                         Up to 0.50% of loan amount
8                   Bajaj Finserv  ...                          Up to 1.5% of loan amount
9        PNB Housing Finance Ltd.  ...                            Up to 2% of loan amount
10                   Tata Capital  ...                            Up to 2% of loan amount
11       LIC Housing Finance Ltd.  ...                                  1% of loan amount
12                      Axis Bank  ...  Rs. 10,000 or 1% of loan amount, whichever is ...

[12 rows x 3 columns]

# 4. Business Loan

In [0]:
source = urllib.request.urlopen('https://www.paisabazaar.com/business-loan/interest-rates/').read()
soup = bs.BeautifulSoup(source,'lxml')

In [0]:
table = soup.find_all('table')
table = table[0]
res = []
table_rows = table.find_all('tr')
for tr in table_rows:
  td = tr.find_all('td')
  row = [tr.text.strip() for tr in td if tr.text.strip()]
  if row:
    res.append(row)
    
res.pop(0)
df = pd.DataFrame(res, columns=["Bank/NBFC/Fintech","Loan Amount (Min)","Loan Amount (Max)","Repayment Tenure (Months)","Interest Rate (p.a.)"])

In [150]:
df

                    Bank/NBFC/Fintech  ... Interest Rate (p.a.)
0                           Axis Bank  ...       14.25% onwards
1                       Bajaj Finserv  ...          15% onwards
2                 Capital First Prime  ...          21% onwards
3                   Fullerton Finance  ...          17% onwards
4         HDB Financial Services Ltd.  ...        15.5% onwards
5                           HDFC Bank  ...          15% onwards
6                        Hero FinCorp  ...          18% onwards
7                          ICICI Bank  ...          15% onwards
8                        IIFL Finance  ...          25% onwards
9                      Indifi Finance  ...          22% onwards
10                Kotak Mahindra Bank  ...          16% onwards
11                Lendingkart Finance  ...          15% onwards
12                  NeoGrowth Finance  ...          24% onwards
13  PaySense Services India Pvt. Ltd.  ...          24% onwards
14                           RBL Bank  ...          16% onwards
15               Tata Capital Finance  ...          17% onwards
16           Yes Bank Working Capital  ...          10% onwards
17                            ZipLoan  ...          24% onwards

[18 rows x 5 columns]

# 5. Car Loan

In [0]:
source = urllib.request.urlopen('https://www.paisabazaar.com/car-loan/interest-rates/').read()
soup = bs.BeautifulSoup(source,'lxml')

In [0]:
table = soup.find('table')
res = []
table_rows = table.find_all('tr')
for tr in table_rows:
  td = tr.find_all('td')
  row = [tr.text.strip() for tr in td if tr.text.strip()]
  if row:
    res.append(row)
df = pd.DataFrame(res, columns=res[0])

df.drop(df.head(1).index, inplace=True)

In [155]:
df

       Bank/Lender Name  ...                               Loan Processing Fees
1                   SBI  ...  0.50% of Loan Amount +ST Min: Rs.950.00 +ST, M...
2             HDFC Bank  ...    Rs.2825 to Rs.5150 (depends on the loan amount)
3            ICICI Bank  ...    Rs.2500 to Rs.5000 (depends on the loan amount)
4             Axis Bank  ...                                 Rs.3500 to Rs.5500
5             IDBI Bank  ...                                                NIL
6  Punjab National Bank  ...               1% of the loan amount. (Max-Rs.6000)
7         Bank of India  ...  Rs.500/- plus S.T. or 1% of loan amount. Min: ...
8        Syndicate Bank  ...  Up to 2 Lakhs: Rs.1.25 per thousand. Minimum: ...

[8 rows x 3 columns]

# 6.Personal loan

In [0]:
source = urllib.request.urlopen('https://www.paisabazaar.com/personal-loan/interest-rates/').read()
soup = bs.BeautifulSoup(source,'lxml')

In [0]:
table = soup.find('table')
res = []
table_rows = table.find_all('tr')
for tr in table_rows:
  td = tr.find_all('td')
  row = [tr.text.strip() for tr in td if tr.text.strip()]
  if row:
    res.append(row)
df = pd.DataFrame(res, columns=res[0])

df.drop(df.head(1).index, inplace=True)

In [157]:
df

                       Bank  ...                        Processing Fees
1            Allahabad Bank  ...               1.60% of the Loan Amount
2               Andhra Bank  ...               As offered by the lender
3                 Axis Bank  ...                  1.50% to 2.00 % + GST
4             Bajaj Finserv  ...         Up to 3.99% of the loan amount
5            Bank of Baroda  ...                  2% of the loan amount
6             Bank of India  ...        One time @ 2.00% of loan amount
7       Bank of Maharashtra  ...               1.00% of the Loan Amount
8               Canara Bank  ...                0.5% of the Loan Amount
9              Central Bank  ...                           Rs 500 + S.T
10                 Citibank  ...              Upto 2.75% of loan amount
11         Corporation Bank  ...               1.50% of the loan amount
12             Federal Bank  ...                   0.50% of loan amount
13          Fullerton India  ...           Upto 6.5% of the loan amount
14                HDFC Bank  ...         Up to 2.50% of the loan amount
15                HSBC Bank  ...  Up to 1% of the disbursed loan amount
16               ICICI Bank  ...   Up to 2.25% per annum of loan amount
17                IDBI Bank  ...                  1% of the Loan Amount
18               IDFC First  ...            Up to 2% of the loan amount
19              Indian Bank  ...               0.51% on the Loan Amount
20            IndusInd Bank  ...  Upto 2.5% of the loan amount plus tax
21      Kotak Mahindra Bank  ...    Up to 2.5% of the loan amount + GST
22          Muthoot Finance  ...            As applicable by the lender
23     Punjab National Bank  ...               1.80% of the loan amount
24                 RBL Bank  ...                  4% of the loan amount
25  Standard Chartered Bank  ...             Upto 3% of the loan amount
26      State Bank of India  ...                  1% of the loan amount
27           Syndicate Bank  ...               0.50% of the loan amount
28             TATA Capital  ...    Up to 2.5% of the loan amount + GST
29                 UCO Bank  ...                  1% of the loan amount
30      Union Bank of India  ...                0.50% of the total Loan
31                 Yes Bank  ...         Up to 2.50% of the loan amount

[31 rows x 3 columns]

# 7. Home Loan

In [0]:
source = urllib.request.urlopen('https://www.paisabazaar.com/home-loan/interest-rates/').read()
soup = bs.BeautifulSoup(source,'lxml')

In [0]:
table = soup.find('table', attrs={'width':'100%'})
res = []
table_rows = table.find_all('tr')
for tr in table_rows:
  td = tr.find_all('td')
  row = [tr.text.strip() for tr in td if tr.text.strip()]
  if row:
    res.append(row)
df = pd.DataFrame(res, columns=res[0])

df.drop(df.head(1).index, inplace=True)

In [162]:
df

                Home Loan Providers  ...                 Processing Fees (exclusive of GST)
1                    Allahabad Bank  ...     0.24% – 0.40% of loan amount (Max. Rs. 50,000)
2                         Axis Bank  ...      Up to 1% of the loan amount (Min. Rs. 10,000)
3                    Bank of Baroda  ...  0.25% – 0.50% of loan amount (Min. Rs. 8,500; ...
4                   Bajaj Finserv**  ...                       0.80% – 1.20% of loan amount
5                     Bank of India  ...  0.25% of loan amount (Min. 1000; Max. Rs. 50,000)
6                       Canara Bank  ...  0.50% of loan amount (Min. Rs. 1,500; Max. Rs....
7             Central Bank of India  ...       Up to 0.50% of loan amount (Max. Rs. 20,000)
8                          Citibank  ...                                    Up to Rs. 5,000
9                          DBS Bank  ...                                   Up to Rs. 10,000
10                             DHFL  ...  Salaried/Self Employed Professional – Rs. 2,50...
11                     Federal Bank  ...  0.50% of loan amount (Min. Rs. 3,000; Max. Rs....
12                        HDFC Bank  ...  Up to 0.5% of loan amount or Rs. 3,000, whiche...
13                       ICICI Bank  ...  0.50% – 1.00% of loan amount or Rs. 1,500 – 20...
14                        IDBI Bank  ...                                   Up to Rs. 10,000
15                  IDFC First Bank  ...                                   Up to Rs. 10,000
16                             IIFL  ...                      Rs 5,000 to 1% of loan amount
17       Indiabulls Housing Finance  ...                            Up to 1% of loan amount
18  India Shelter Finance Corp. Ltd  ...                             2% – 3% of loan amount
19             Indian Overseas Bank  ...                     Up to 1.20% of the loan amount
20              Kotak Mahindra Bank  ...                            Up to 2% of loan amount
21              LIC Housing Finance  ...                                      As applicable
22             Punjab National Bank  ...  0.35% of loan amount (Min. Rs. 2,500; Max. Rs....
23              PNB Housing Finance  ...                            Up to 1% of loan amount
24            Reliance Home Finance  ...                        0.50% – 1.5% of loan amount
25                              SBI  ...  0.35% – 0.50% of loan amount (Min. Rs. 2,000; ...
26          Standard Chartered Bank  ...                            Up to 1% of loan amount
27                   Syndicate Bank  ...  0.125% of loan amount (Min. Rs. 500; Max. Rs. ...
28                     Tata Capital  ...                            Up to 2% of loan amount
29             United Bank of India  ...  0.59% of loan amount (Min. Rs.1,180; Max. Rs.1...
30                         YES Bank  ...  2% of loan amount or Rs. 10,000, whichever is ...

[30 rows x 3 columns]

# 8. Education Loan

In [0]:
source = urllib.request.urlopen('https://www.paisabazaar.com/education-loan/interest-rates/').read()
soup = bs.BeautifulSoup(source,'lxml')

In [0]:
table = soup.find('table')
res = []
table_rows = table.find_all('tr')
for tr in table_rows:
  td = tr.find_all('td')
  row = [tr.text.strip() for tr in td if tr.text.strip()]
  if row:
    res.append(row)
df = pd.DataFrame(res, columns=res[0])

df.drop(df.head(1).index, inplace=True)

In [165]:
df

                                           Banks/NBFC  ... Rate of Interest
1                                           Axis Bank  ...           15.20%
2   Loans greater than Rs. 4 Lakhs and upto Rs. 7....  ...             None
3                    Loans greater than Rs. 7.5 Lakhs  ...             None
4                                      Bank of Baroda  ...    8.50% onwards
5                                         Canara Bank  ...            6.60%
6                                   Up to Rs. 4 Lakhs  ...             None
7                       Rs. 4 Lakhs to Rs. 7.50 Lakhs  ...             None
8                          Loans above Rs. 7.50 lakhs  ...             None
9   IBA´s Model Loan scheme for Vocational Educati...  ...             None
10                                          HDFC Bank  ...            9.00%
11                                        Maximum APR  ...             None
12                                        Average APR  ...             None
13                                Kotak Mahindra Bank  ...     11.5% to 24%
14                               Punjab National Bank  ...    8.55% onwards
15                                PNB Saraswati/Udaan  ...             None
16  PNB Pratibha (for admission to IITs , IIMs and...  ...             None
17     PNB Pratibha (for admission to other colleges)  ...             None
18                                        PNB Honhaar  ...             None
19                                State Bank of India  ...           10.25%
20                                Above Rs. 7.5 Lakhs  ...             None
21                                             Avanse  ...    10% to 16.50%
22                                            Credila  ...   11.85% onwards

[22 rows x 3 columns]